2021-12-22 12:01:07 India Standard Time, uvicorn.error, 20872, ERROR, path=C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py, lineno=376, request_span_id=3JB5BA1B1M , message=Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\bytelearn-teacher-backend\middlewares\context_set_request_middleware.py", line 31, in dispatch
    response = await call_next(request)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 45, in call_next
    task.result()
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\bytelearn-teacher-backend\middlewares\request_log_middleware.py", line 30, in dispatch
    response = await call_next(request)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 45, in call_next
    task.result()
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\bytelearn-teacher-backend\teacher_dashboard\GoogleClassroom\google_classroom.py", line 150, in list_google_courses
    courses_list = google_classroom_courses(
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\bytelearn-teacher-backend\teacher_dashboard\GoogleClassroom\google_classroom.py", line 133, in google_classroom_courses
    student_dict['email'] = student['profile']['emailAdrress']
KeyError: 'emailAdrress'
2021-12-22 12:03:22 India Standard Time, uvicorn.error, 31820, ERROR, path=C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py, lineno=376, request_span_id=FQOREL09OR , message=Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\bytelearn-teacher-backend\middlewares\context_set_request_middleware.py", line 31, in dispatch
    response = await call_next(request)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 45, in call_next
    task.result()
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\bytelearn-teacher-backend\middlewares\request_log_middleware.py", line 30, in dispatch
    response = await call_next(request)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 45, in call_next
    task.result()
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\bytelearn-teacher-backend\teacher_dashboard\GoogleClassroom\google_classroom.py", line 151, in list_google_courses
    courses_list = google_classroom_courses(
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\bytelearn-teacher-backend\teacher_dashboard\GoogleClassroom\google_classroom.py", line 133, in google_classroom_courses
    student_dict['email'] = student['profile']['emailAddress']
KeyError: 'emailAddress'
2021-12-22 12:19:24 India Standard Time, uvicorn.error, 3396, ERROR, path=C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py, lineno=376, request_span_id=QKWLB8AV2X , message=Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\bytelearn-teacher-backend\middlewares\context_set_request_middleware.py", line 31, in dispatch
    response = await call_next(request)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 45, in call_next
    task.result()
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\bytelearn-teacher-backend\middlewares\request_log_middleware.py", line 30, in dispatch
    response = await call_next(request)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 45, in call_next
    task.result()
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\bytelearn-teacher-backend\teacher_dashboard\GoogleClassroom\google_classroom.py", line 166, in connect_google_courses
    courses_list = google_classroom_courses(
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\bytelearn-teacher-backend\teacher_dashboard\GoogleClassroom\google_classroom.py", line 107, in google_classroom_courses
    if class_crud.get_teacher_classes_by_google_id(db=db, teacher_id=teacher_id, google_id=course['id']) is not None:
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\bytelearn-teacher-backend\teacher_dashboard\Classes\class_crud.py", line 152, in get_teacher_classes_by_google_id
    db_class = db.query(models.Classes).filter(models.Classes.teacher_id == teacher_id,models.Classes.google_id == google_id).first()
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2762, in first
    return self.limit(1)._iter().first()
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2846, in _iter
    result = self.session.execute(
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: SELECT test_classes.id AS test_classes_id, test_classes.google_id AS test_classes_google_id, test_classes.source AS test_classes_source, test_classes.`status` AS test_classes_status, test_classes.name AS test_classes_name, test_classes.code AS test_classes_code, test_classes.teacher_id AS test_classes_teacher_id, test_classes.created_at AS test_classes_created_at, test_classes.updated_at AS test_classes_updated_at, test_classes.student_count AS test_classes_student_count 
FROM test_classes 
WHERE test_classes.teacher_id = %s AND test_classes.google_id = %s 
 LIMIT %s]
[parameters: ('0375b704-91b2-4ff6-afca-8418d54e0d9d', '402765136934', 1)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2021-12-22 12:20:45 India Standard Time, uvicorn.error, 3396, ERROR, path=C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py, lineno=376, request_span_id=YLBHAMU0LZ , message=Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 26, in __call__
    await response(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\responses.py", line 224, in __call__
    await run_until_first_complete(
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\concurrency.py", line 24, in run_until_first_complete
    [task.result() for task in done]
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\concurrency.py", line 24, in <listcomp>
    [task.result() for task in done]
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\responses.py", line 216, in stream_response
    async for chunk in self.body_iterator:
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 56, in body_stream
    task.result()
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 26, in __call__
    await response(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\responses.py", line 224, in __call__
    await run_until_first_complete(
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\concurrency.py", line 24, in run_until_first_complete
    [task.result() for task in done]
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\concurrency.py", line 24, in <listcomp>
    [task.result() for task in done]
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\responses.py", line 216, in stream_response
    async for chunk in self.body_iterator:
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 56, in body_stream
    task.result()
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\starlette\exceptions.py", line 86, in __call__
    raise RuntimeError(msg) from exc
RuntimeError: Caught handled exception, but response already started.
2021-12-22 12:35:08 India Standard Time, uvicorn.error, 14992, ERROR, path=C:\Users\KUNDAN\Desktop\TeacherDashboard\venv\lib\site-packages\uvicorn\server.py, lineno=167, request_span_id=None , message=[Errno 10048] error while attempting to bind on address ('127.0.0.1', 5000): only one usage of each socket address (protocol/network address/port) is normally permitted
